### ISSUE TITLE
should there be semicolons? 

### ISSUE THREAD

**Issue by bmoren** [bmoren/p5js-cheat-sheet#18]
+ They are debatable as the there requirement as it is 
+ They add a lot of visual weight
+ They are present in the other official p5js documentation. 

@limzykenneth, @rich-gg, @Philipp-Lehmann, @vincentsijben do you have any opinions about this?

@lmccart did the semi colon ever come up as a discussion point in the documentation style of p5js?

**Comment by vincentsijben** [comment]
I think as for students who arent programming with functions on every new line, it becomes a problem real quickly. Also, with the relationship of p5js and processing, it would be best practise. I dont think they add that lot of weight. You're doing it with the vertices as well :)

**Comment by limzykenneth** [comment]
For p5.js the coding style rules are based on `eslint:recommended` rules with various extensions. The semicolon rule came from there and so all p5.js codebase have semicolons in order to pass linting. 

As far as I know there isn't much discussion around that issue as code style is not something we want to enforce too strictly, prefering to have automated tools fix these things instead of requiring a beginner to do one thing instead of another.

**Comment by bmoren** [comment]
This makes sense to me – in that case @vincentsijben lets go ahead and add semi's to the function calls! It makes sense to me to keep things in parity with the official p5js documentation for easy transition.
